projectGroup=yue.chip
projectVersion=zunyi-1.0.3-SNAPSHOT
jdkVersion=17
org.gradle.caching=true
org.gradle.parallel=true
mavenRepository=http://nexus.smartxwei.com:8081/repository/maven-public/
mavenSnapshots=http://nexus.smartxwei.com:8081/repository/maven-snapshots/
mavenUsername=admin
mavenPassword=admin
springBootVersion=3.4.2
lombokVersion=1.18.34
mapstructVersion=1.6.0
yueChipPlatformVersion=1.0.3-back-SNAPSHOT
nativeVersion=0.9.20
commonBusinessVersion=zunyi-1.0.3-SNAPSHOT