projectGroup=yue.chip
projectVersion=1.0.2-iot-business-SNAPSHOT
jdkVersion=17
org.gradle.caching=true
org.gradle.parallel=true
mavenRepository=http://192.168.11.202:8081/repository/maven-public/
mavenSnapshots=http://192.168.11.202:8081/repository/maven-snapshots/
mavenUsername=admin
mavenPassword=admin
springBootVersion=3.4.1
lombokVersion=1.18.36
mapstructVersion=1.6.3
yueChipPlatformVersion=1.0.2-SNAPSHOT
nativeVersion=0.9.20
commonBusinessVersion=1.0.2-iot-business-SNAPSHOT