plugins {
    id 'org.springframework.boot' version "${springBootVersion}"
    id 'application'
//    id 'org.graalvm.buildtools.native' version "${nativeVersion}"
}
archivesBaseName = 'yue-chip-upms-server'
apply plugin: 'org.springframework.boot'
apply from: this.rootProject.file('javaLibrary.gradle')
apply from: this.rootProject.file('javaLibraryMvnPublish.gradle')
configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
    testCompileOnly {
        extendsFrom testAnnotationProcessor
    }
}
mainClassName = 'com.yue.chip.upms.ApplicationUpmsServe'
//graalvmNative {
//    binaries {
//        main {
//            verbose = true
//            fallback = true
//            buildArgs.add('-H:+ReportExceptionStackTraces')
//            buildArgs.add('--no-fallback')
//            buildArgs.add('--report-unsupported-elements-at-runtime')
//            buildArgs.add('--allow-incomplete-classpath')
//            buildArgs.add('--initialize-at-build-time=org.slf4j.LoggerFactory,ch.qos.logback.classic.Logger,java.net.Inet4Address')
//            buildArgs.add('--trace-class-initialization=org.slf4j.LoggerFactory,ch.qos.logback.classic.Logger,java.net.Inet4Address')
//            buildArgs.add('--trace-object-instantiation=java.net.Inet4Address')
//        }
//    }
//}
bootJar {
    enabled true
}
dependencies {
    api project(':interface-expose')
    api project(':authentication')
    api ('com.primeton.epas:pas-spring-boot-starter:6.5.1')
    api ('com.primeton.epas:pas-embed-core:6.5.1')
    api ('com.primeton.epas:pas-embed-el:6.5.1')
    api ('com.primeton.epas:pas-embed-websocket:6.5.1')
    api ('com.primeton.epas:pas-spring-websocket-adapter:6.5.1')
    api platform("yue.chip:starter:${yueChipPlatformVersion}"){
        exclude(group:'org.apache.tomcat.embed',module:'tomcat-embed-core')
        exclude(group:'org.apache.tomcat.embed',module:'tomcat-embed-el')
        exclude(group:'org.apache.tomcat.embed',module:'tomcat-embed-websocket')
    }
    api ('yue.chip:yue-chip-serve-starter'){
        exclude(group:'org.apache.tomcat.embed',module:'tomcat-embed-core')
        exclude(group:'org.apache.tomcat.embed',module:'tomcat-embed-el')
        exclude(group:'org.apache.tomcat.embed',module:'tomcat-embed-websocket')
    }
    api ('yue.chip:yue-chip-business-starter'){
        exclude(group:'org.apache.tomcat.embed',module:'tomcat-embed-core')
        exclude(group:'org.apache.tomcat.embed',module:'tomcat-embed-el')
        exclude(group:'org.apache.tomcat.embed',module:'tomcat-embed-websocket')
    }
    api ("yue.chip:yue-chip-common-business-interface-expose:${commonBusinessVersion}"){
        exclude(group:'org.apache.tomcat.embed',module:'tomcat-embed-core')
        exclude(group:'org.apache.tomcat.embed',module:'tomcat-embed-el')
        exclude(group:'org.apache.tomcat.embed',module:'tomcat-embed-websocket')
    }
//    api 'yue.chip:yue-chip-security'
//    api "yue.chip:yue-chip-oauth2-resource-server"
//    implementation 'org.springframework.boot:spring-boot-devtools'
    api 'org.apache.poi:poi-ooxml:4.1.2'
    api "org.springframework.statemachine:spring-statemachine-starter"
    api "org.springframework.statemachine:spring-statemachine-data-redis"
    api "org.springframework.statemachine:spring-statemachine-data-jpa"
    api 'cn.com.kingbase:kingbase8:8.6.0'
    api 'xiao.wei:hibernate:6.2'
    api 'com.sun.messaging.mq:fscontext:4.6-b01'
    implementation('org.springframework.boot:spring-boot-starter-data-jdbc') {
        exclude group: 'org.springframework.data', module: 'spring-data-jdbc'
    }
    compileOnly "org.mapstruct:mapstruct"
    compileOnly "org.mapstruct:mapstruct-processor"
    compileOnly "org.mapstruct:mapstruct-jdk8"
    compileOnly "org.projectlombok:lombok"
    compileOnly "org.projectlombok:lombok-mapstruct-binding"
    annotationProcessor "org.projectlombok:lombok:${lombokVersion}"
    testCompileOnly "org.projectlombok:lombok:${lombokVersion}"
    testAnnotationProcessor "org.projectlombok:lombok:${lombokVersion}"
    annotationProcessor "org.mapstruct:mapstruct-processor:${mapstructVersion}"
    testCompileOnly "org.mapstruct:mapstruct-processor:${mapstructVersion}"
    testAnnotationProcessor"org.mapstruct:mapstruct-processor:${mapstructVersion}"
}

